/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class VagabondActor extends Actor {

  /** @override */
  static getDefaultArtwork(actorData) {
    // 1. Check if the actor being created is an NPC
    if (actorData.type === "npc") {
      // 2. HARDCODE the path here to ensure no config errors
      const img = "systems/vagabond/assets/ui/default-npc.svg";
      
      return {
        img: img,
        texture: { src: img }
      };
    }

    // 3. Fallback for characters or other types
    return super.getDefaultArtwork(actorData);
  }

  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets.
   */
  prepareDerivedData() {
    // ---------------------------------------------------------------
    // TRIGGER DATA MODEL CALCULATIONS
    // This calls this.system.prepareDerivedData() automatically.
    // Class data is already loaded in the DataModel's prepareBaseData(),
    // and Active Effects have been applied between prepareBaseData and here.
    // ---------------------------------------------------------------
    super.prepareDerivedData();

    // ---------------------------------------------------------------
    // Flags and other post-calculation logic
    // ---------------------------------------------------------------
    const actorData = this;
    const flags = actorData.flags.vagabond || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }
}