/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class VagabondActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.vagabond || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * @override
   * Update tracking values for NPC HP recalculation after update
   */
  async _preUpdate(changed, options, user) {
    await super._preUpdate(changed, options, user);

    // For NPCs, track HD and size changes for HP recalculation
    if (this.type === 'npc') {
      const hdChanged = changed.system?.hd !== undefined;
      const sizeChanged = changed.system?.size !== undefined;

      if (hdChanged || sizeChanged) {
        // Update tracking values
        changed.system = changed.system || {};
        changed.system._lastHD = changed.system.hd ?? this.system.hd;
        changed.system._lastSize = changed.system.size ?? this.system.size;
      }
    }
  }
}
